"""add timezone to User model

Revision ID: 026d41b429f0
Revises: 9f53ccef38d0
Create Date: 2025-04-29 19:44:12.008652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '026d41b429f0'
down_revision = '9f53ccef38d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('timezone')

    # ### end Alembic commands ###
