"""Add category and day columns to Memory model

Revision ID: 30edd2e1c77a
Revises: 35490152754b
Create Date: 2025-04-23 10:29:01.022653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30edd2e1c77a'
down_revision = '35490152754b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('day', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memory', schema=None) as batch_op:
        batch_op.drop_column('day')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
