"""add tags and lead to Conversation

Revision ID: 9f53ccef38d0
Revises: ea62fd9150e1
Create Date: 2025-04-29 18:59:42.751995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f53ccef38d0'
down_revision = 'ea62fd9150e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('lead', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_column('lead')
        batch_op.drop_column('tags')

    # ### end Alembic commands ###
