"""Add schedule_id to Memory for multi-schedule support

Revision ID: ea62fd9150e1
Revises: 30edd2e1c77a
Create Date: 2025-04-23 12:48:08.965393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea62fd9150e1'
down_revision = '30edd2e1c77a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule_id', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memory', schema=None) as batch_op:
        batch_op.drop_column('schedule_id')

    # ### end Alembic commands ###
